import pandas as pd
import matplotlib.pyplot as plt

# Input generated by your pipeline
df = pd.read_csv("per_codon_table.tsv", sep="\t")

# ---------- Figure 1: Slow codon proportion by region ----------
summary = df.groupby("region")["is_slow"].agg(["sum","count"])
summary["pct_slow"] = 100 * summary["sum"] / summary["count"]

plt.figure()
plt.bar(summary.index, summary["pct_slow"])
plt.ylabel("% slow codons")
plt.title("Figure 1. Slow-codon proportion by region")
plt.savefig("Figure1_slow_percent_by_region.png", dpi=300, bbox_inches="tight")
plt.close()

# ---------- Figure 2: Distribution of w by region (histograms) ----------
plt.figure()
for region in df["region"].unique():
    sub = df[df["region"] == region]["w"].dropna().astype(float)
    plt.hist(sub, bins=30, alpha=0.6, label=region)

plt.xlabel("Codon adaptiveness weight (w)")
plt.ylabel("Count")
plt.title("Figure 2. Distribution of codon weights (w) by region")
plt.legend()
plt.savefig("Figure2_w_distribution_by_region.png", dpi=300, bbox_inches="tight")
plt.close()

print("Saved: Figure1_slow_percent_by_region.png, Figure2_w_distribution_by_region.png")
